// <auto-generated />
using System;
using EVoterAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVoterAPI.Migrations
{
    [DbContext(typeof(EVoterContext))]
    [Migration("20211121180548_MigrationV1")]
    partial class MigrationV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_VoterApi.Models.Election", b =>
                {
                    b.Property<Guid>("electionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("electionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("electionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("electionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("modifiedTicks")
                        .HasColumnType("bigint");

                    b.Property<int?>("totalVotes")
                        .HasColumnType("int");

                    b.Property<Guid>("winnerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("electionID");

                    b.ToTable("Election");
                });

            modelBuilder.Entity("E_VoterApi.Models.ElectionResult", b =>
                {
                    b.Property<Guid>("electionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("nomineeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ranking")
                        .HasColumnType("int");

                    b.Property<int>("totalVotes")
                        .HasColumnType("int");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("E_VoterApi.Models.Nominee", b =>
                {
                    b.Property<Guid>("electionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("association")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("userID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("electionID");

                    b.ToTable("Nominee");
                });

            modelBuilder.Entity("E_VoterApi.Models.User", b =>
                {
                    b.Property<Guid>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("modifiedTicks")
                        .HasColumnType("bigint");

                    b.HasKey("userID");

                    b.ToTable("VoterUsers");
                });

            modelBuilder.Entity("E_VoterApi.Models.Vote", b =>
                {
                    b.Property<Guid>("voteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("electionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("modifiedTicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("modifiedTicks"), 1L, 1);

                    b.Property<Guid>("nomineeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("voterID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("voteID");

                    b.ToTable("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
